// src/components/Cell.vue
<template>
  <div id="cell" :style="cellStyle">
    <span id="ship" v-if="isShip" :style="shipStyle">
      <i class="fas fa-space-shuttle"></i>
    </span>
    <span id="star" v-if="star && !star.collected">
      <i class="fas fa-star"></i>
    </span>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue'
import { useStore, Cell , Color, Direction } from '../store'

export default defineComponent({
  name: 'Cell',
  props: {
    row: {
      type: Number,
      required: true
    },
    col: {
      type: Number,
      required: true
    }
  },
  setup: (props) => {
    const store = useStore()

    const cell = computed(() => {
      const instore = store.state.grid.cells.find(c => c.row === props.row && c.col === props.col)
      return instore || { row: props.row, col: props.col, color: Color.NONE } as Cell
    })

    const background = computed(() => store.getters.getCSSColor(cell.value.color))

    const isShip = computed(() => store.state.grid.ship.row === props.row && store.state.grid.ship.col === props.col)
    const star = computed(() => store.state.grid.stars.find(star => star.row === props.row && star.col === props.col))

    watch(
      () => isShip.value,
      (value) => {
        if (!value || !star.value || star.value?.collected) return
        store.commit("collect", { row: props.row, col: props.col })
      }
    )

    const cellStyle = computed(() => ({
      "borderRadius": "8px",
      "box-shadow": "0 0 8px 0 rgba(0, 0, 0, 0.08), 0 0 20px 0 rgba(0, 0, 0, 0.05)",
      ...(cell.value.color ? { "background": background.value } : {}),
      ...(cell.value.color === Color.NONE ? { border: "" } : {})
    }))

    const shipStyle = computed(() => ({
      "color": cell.value.color === Color.NONE ? "black" : "white",
      ...(store.state.grid.ship.direction === Direction.TOP ? { "transform": "rotate(-90deg)" } : {}),
      ...(store.state.grid.ship.direction === Direction.RIGHT ? { "transform": "rotate(0deg)" } : {}),
      ...(store.state.grid.ship.direction === Direction.BOTTOM ? { "transform": "rotate(90deg)" } : {}),
      ...(store.state.grid.ship.direction === Direction.LEFT ? { "transform": "rotate(180deg)" } : {})
    }))

    return {
      cellStyle,
      isShip,
      shipStyle,
      star
    }
  }
})
</script>

<style scoped>
#star {
  height: 100%;

  display: flex;
  justify-content: center;
  align-items: center;

  color: white;
}
#ship {
  height: 100%;

  display: flex;
  justify-content: center;
  align-items: center;

  color: white;
}
</style>

// src/components/Cell.tsx
import { Component, createMemo, Show } from "solid-js"
import { Cell as ICell, Color, gameStore, makeEmptyCell } from "../store";
import {useLevel} from "../context/Level";

export interface CellProps {
  row: number;
  col: number;
}

const COLORS: Record<Color, string> = {
  "NONE": "bg-white",
  "RED": "bg-red-500",
  "BLUE": "bg-blue-500",
  "GREEN": "bg-green-500"
}

const Cell: Component<CellProps> = (props: CellProps) => {
  const { row, col } = props

  const [state] = gameStore
  const { level } = useLevel()

  const cell = createMemo<ICell>(() => {
    const found = level().cells.find(c => c.row === row && c.col === col)
    return found || makeEmptyCell(row, col)
  })
  const bg = createMemo(() => {
    return COLORS[cell().color]
  })

  const isStar = createMemo<boolean>(() => {
    const star = level().stars.find(s => s.row === row && s.col === col)
    if (!star) return false;

    const collected = state.game.starsCollected.find(s => s.col === star.col && s.row === star.row)
    return !collected
  })

  const isShip = createMemo<boolean>(() => {
    const s = state.game.ship
    return s.col === col && s.row === row
  })

  const rotate = createMemo<string>(() => {
    if (!isShip()) return ""

    const s = level().ship
    if (s.dir === "TOP") {
      return "-rotate-90"
    } else if (s.dir === "LEFT") {
      return "rotate-180"
    } else if (s.dir === "RIGHT") {
      return "rotate-0"
    } else if (s.dir === "BOTTOM") {
      return "rotate-90"
    }
    throw new Error("Missing rotation value")
  })

  const color = createMemo(() => {
    return cell().color === "NONE" ? "text-black" : "text-white"
  })

  return (
    <div
      class={`w-14 flex justify-center items-center rounded-2xl aspect-square text-xl ${bg()} ${rotate()} ${color()}`}
      style="box-shadow: 0 0 8px 0 rgba(0, 0, 0, 0.08), 0 0 20px 0 rgba(0, 0, 0, 0.05);"
    >
      <Show when={isStar()}>
        <i class="fas fa-star"></i>
      </Show>
      <Show when={isShip()}>
        <i class="fas fa-space-shuttle"></i>
      </Show>
    </div>
  )
}
export default Cell
